// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a structured API error response.
 */
export type ApiErrorResponse = { 
/**
 * Always "ERROR" for error responses.
 */
status: string, 
/**
 * Stable machine-readable error code.
 */
code: string, 
/**
 * User-facing error message.
 */
message: string, 
/**
 * Safe error reason for compatibility.
 */
reason: string, };

export type AppVersionCheckPayload = { client_version: string, };

export type AppVersionInfo = { minimum_required_version: string, update_required: boolean, };

/**
 * Represents events that can occur during LNURL-auth.
 */
export type AuthEvent = "REGISTERED";

export type AuthLoginPayload = { key: string, sig: string, k1: string, };

export type AuthLoginResponse = { access_token: string, token_type: string, expires_at: string, expires_in_seconds: number, };

/**
 * Defines the payload for granting mailbox authorization to the server.
 */
export type AuthorizeMailboxPayload = { 
/**
 * Ark mailbox identifier scoped to the loaded wallet.
 */
mailbox_id: string, 
/**
 * Authorization expiry as a Unix timestamp in seconds.
 */
expiry: number, 
/**
 * Hex-encoded mailbox authorization.
 */
encoded: string, };

export type BackupInfo = { backup_version: number, created_at: string, backup_size: number, };

export type BackupSettingsPayload = { backup_enabled: boolean, };

export type BackupTriggerNotification = { notification_k1: string, };

export type CompleteUploadPayload = { s3_key: string, backup_version: number, backup_size: number, };

export type DefaultSuccessPayload = { success: boolean, };

export type DeleteBackupPayload = { backup_version: number, };

/**
 * Defines device information captured during registration.
 */
export type DeviceInfo = { device_manufacturer: string | null, device_model: string | null, os_name: string | null, os_version: string | null, app_version: string | null, };

export type DownloadUrlResponse = { download_url: string, backup_size: number, };

/**
 * Represents the response for email verification requests.
 */
export type EmailVerificationResponse = { success: boolean, message: string | null, };

export type GetDownloadUrlPayload = { backup_version: number | null, };

export type GetUploadUrlPayload = { backup_version: number, };

export type HeartbeatNotification = { notification_id: string, };

export type HeartbeatResponsePayload = { notification_id: string, };

/**
 * Defines the payload for querying lightning address suggestions.
 */
export type LightningAddressSuggestionsPayload = { 
/**
 * Partial lightning address typed in the send screen.
 */
query: string, };

/**
 * Represents autocomplete suggestions for lightning addresses.
 */
export type LightningAddressSuggestionsResponse = { 
/**
 * Ordered suggestion list.
 */
suggestions: Array<string>, };

export type LightningClaimRequestNotification = { payment_hash: string | null, amount_sat: number | null, };

export type LightningInvoiceRequestNotification = { transaction_id: string, amount: number, };

export type MaintenanceNotification = { notification_k1: string, };

export type NotificationData = { "notification_type": "maintenance" } & MaintenanceNotification | { "notification_type": "lightning_invoice_request" } & LightningInvoiceRequestNotification | { "notification_type": "lightning_claim_request" } & LightningClaimRequestNotification | { "notification_type": "backup_trigger" } & BackupTriggerNotification | { "notification_type": "heartbeat" } & HeartbeatNotification;

/**
 * Defines the payload for a user registration request.
 */
export type RegisterPayload = { 
/**
 * User chosen lightning address
 */
ln_address: string | null, 
/**
 * Optional device information.
 */
device_info: DeviceInfo | null, 
/**
 * Optional Ark address
 */
ark_address: string | null, };

/**
 * Defines the payload for registering a push notification token.
 */
export type RegisterPushToken = { 
/**
 * The Expo push token for the user's device.
 */
push_token: string, };

/**
 * Represents the response for an user registration.
 */
export type RegisterResponse = { 
/**
 * The status of the request, either "OK" or "ERROR".
 */
status: string, 
/**
 * An optional event indicating the outcome of the authentication.
 */
event: AuthEvent | null, 
/**
 * An optional reason for an error, if one occurred.
 */
reason: string | null, 
/**
 * The user's lightning address.
 */
lightning_address: string | null, 
/**
 * The user's optional display name.
 */
display_name: string | null, 
/**
 * Whether the user's email is verified.
 */
is_email_verified: boolean, 
/**
 * The user's current operational lifecycle status.
 */
user_status: UserStatus, };

export type ReportJobStatusPayload = { notification_k1: string, report_type: ReportType, status: ReportStatus, error_message: string | null, };

export type ReportStatus = "pending" | "success" | "failure" | "timeout";

export type ReportType = "maintenance" | "backup";

/**
 * Defines the payload for requesting an email verification code.
 */
export type SendEmailVerificationPayload = { email: string, };

/**
 * Defines the payload for submitting a BOLT11 invoice.
 */
export type SubmitInvoicePayload = { 
/**
 * The BOLT11 invoice to be paid.
 */
invoice: string, 
/**
 * The unique identifier for the payment transaction.
 */
transaction_id: string, };

/**
 * Defines the payload for updating a user's lightning address.
 */
export type UpdateLnAddressPayload = { 
/**
 * The new lightning address for the user.
 */
ln_address: string, };

/**
 * Defines the payload for updating a user's profile.
 */
export type UpdateProfilePayload = { 
/**
 * The user's optional display name. Null or empty clears the name.
 */
display_name: string | null, };

export type UploadUrlResponse = { upload_url: string, s3_key: string, };

/**
 * Represents the response for a user's information.
 */
export type UserInfoResponse = { 
/**
 * The user's lightning address.
 */
lightning_address: string, 
/**
 * The user's optional display name.
 */
display_name: string | null, 
/**
 * The user's current operational lifecycle status.
 */
user_status: UserStatus, };

export type UserStatus = "active" | "inactive" | "deregistered";

/**
 * Defines the payload for verifying an email with a code.
 */
export type VerifyEmailPayload = { code: string, };
